### PR TITLE
feat: multiple & configureSecond

### PR DESCRIPTION
**Pull request by reslear**
@johannschopplich you need to do a review and apply eslint formatting since github.dev doesn't support it :) 

### 🔗 Linked issue

closes https://github.com/johannschopplich/nuxt-gtag/issues/30

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme or JSDoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

sources:
- https://developers.google.com/tag-platform/gtagjs/configure#example
- https://developers.google.com/tag-platform/gtagjs/routing
- https://stackoverflow.com/a/73132469

### CODE REVIEW

**Comment by johannschopplich** [comment]
I will probably refactor the API a bit, but thanks for the effort nonetheless!

**Comment by johannschopplich** [comment]
@reslear Thanks a lot for the PR, it was inspiring. I implemented it a bit different tho in https://github.com/johannschopplich/nuxt-gtag/commit/aedc6e44a82c343d9eff0216dd1878ea09260656.

**Comment by reslear** [comment]
@johannschopplich 
Honestly, I'm disappointed. I'm sorry:
- you've over-complicated the code :)))) 
- and forgot to dynamically add grantConsent to the ids array

**Comment by johannschopplich** [comment]
Feel free to iterate once the next version is released and open a PR with simplifications. 🙌

**Comment by johannschopplich** [comment]
@reslear I've released v1.2.0. Thanks for the hint on the init for multiple IDs. Would you mind doing a review on the latest code changes? Thanks in advance. 🙂

**Comment by reslear** [comment]
@johannschopplich how implement analogue https://github.com/johannschopplich/nuxt-gtag/pull/31/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R253 ?

**Comment by johannschopplich** [comment]
@reslear Can you just define it in the module options beforehand? This is possible now and doesn't require a call like `configureSecond` at runtime:

Does this meet your requirements:
```ts
// `nuxt.config.ts`
export default defineNuxtConfig({
  modules: ['nuxt-gtag'],

  gtag: {
    tags: [
      {
        id: 'GT-XXXXXXXXXX',
        config: {
          page_title: 'GA4'
        }
      },
      {
        id: 'DC-ZZZZZZZZZZ',
        config: {
          page_title: 'Floodlight'
        }
      }
    ]
  }
})
```

**Comment by reslear** [comment]
@johannschopplich do you know what dynamic data is? 
https://nuxt.com/docs/api/composables/use-async-data

**Comment by johannschopplich** [comment]
Yep, I've built [Nuxt API Party](https://nuxt-api-party.byjohann.dev/) based on it.

Your function `configureSecond` uses `gtag` under the hood. Can't you create a wrapper around it in your project? I don't get what's missing in my implementation.

If you think there's something missing, please open an issue and gladly open a new PR with your ideas. Thanks!

**Comment by reslear** [comment]
yeah, no problem, I was just suggesting using Sugar's syntax. Thanks!

**Pull request closed without merging**
